### ISSUE TITLE
Error when importing ServerClient in node + typescript backend

### ISSUE THREAD

**Issue by jnwork** [microsoft/tsiclient#319]
Dear devs,

I'd love to use this handy library to access TSI events but I am struggling to make it work, so I'm looking forward for your input / support!
I'm trying to use only the **ServerClient** in a node + typescript backend, but `ts-node` already fails on the import statement:

### Error
```sh
> ts-node bin/receive.ts
<project_path>/node_modules/tsiclient/ServerClient.js:1
import './tslib.es6-e303de9b.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (<project_path>/bin/receive.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1056:23)
```

### Code
`<project_path>/bin/receive.ts`
```js
import ServerClient from 'tsiclient/ServerClient'
const tsiClient = new ServerClient()
const tsi = await tsiClient.getTsqResults(token, tsiURI, [body])
```

### Config
- node 14.16.0
- typescript 4.2.4
- tsiclient 1.4.12
- `tsconfig.json`:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2019",
    "lib": ["es2019", "esnext.asynciterable", "dom"],
    "moduleResolution": "node",
    "esModuleInterop": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "resolveJsonModule": true,
    "outDir": "dist",
    "typeRoots": [ "types",  "node_modules/@types"],
    "baseUrl": ".",
    "paths": {
      "@config": [ "src/config"],
      "@models": [ "src/models"],
      "@models/*": [ "src/models/*"],
      "@util/*": [ "src/util/*"]
    }, 
    "noImplicitReturns": true,
    "strict": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true
  },
  "include": [
    "**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

I made a couple of changes to the tsconfig, to no avail, and I am at my wit's end.
Thanks in advance for any hints and pointers! :)

**Comment by ccrowley96** [comment]
@jnwork TsiClient was written to be consumed in the browser.  We do bundle for `umd` but none of our package imports are tested in a Node environment.  

If you're able to link a minimal reproduction repo, I can take a look, but officially, this use case is not currently supported.
